### ISSUE TITLE
Please tag source code to match released versions

### ISSUE THREAD

**Issue by timovandeput** [material-foundation/material-color-utilities#27]
Without release tags it is not possible to trace the source code for released versions (like 0.1.3 in the Dart Pub.dev package manager).

Please tag the source code for every release.

**Comment by guidezpl** [comment]
It's not practical to tag releases since each library moves at its own pace. However, uUder a package's pub version, you can download an archive of the package at that version number, which will always be accurate.
<img width="237" alt="image" src="https://user-images.githubusercontent.com/6655696/217813868-7c1d0676-2f00-4da2-a0e8-cb9e3106050e.png">
